### PR TITLE
Adds features option to use either time or chrono for sqlx

### PR DESCRIPTION
**Pull request by karuna**
Adds features option to use either time or chrono for sqlx

### CODE REVIEW

**Comment by maxcountryman** [comment]
Thanks for this. I can't publish it until later, but I'll go ahead and merge.

**Comment by maxcountryman** [comment]
Oops, I missed that this breaks feature unification. I'll have to roll this back. I'm not sure what the "right" approach is, but note that `sqlx` doesn't break feature unification so I'd prefer that we don't either. I'm going to revert this for the time being.

**Comment by abonander** [comment]
@maxcountryman I would recommend maybe just using the `chrono` feature, as it's lower in precedence than the `time` feature and will never override it.

Had we better understood feature unification when we were initially designing SQLx, we might have avoided this issue entirely, but the choice is rather ossified at this point.

Even once https://github.com/launchbadge/sqlx/pull/3383 is fully implemented, I'm not sure what to do with the existing behavior except maybe force the user to pick an option.

**Comment by aschweig** [comment]
Does something [like this](https://github.com/aschweig/tower-sessions-stores/tree/chronofix/sqlx-store) not work or has too poor ergonomics?

Cargo.toml
```
[features]
sqlite = ["sqlx/sqlite", "sqlx/time"]
postgres = ["sqlx/postgres", "sqlx/time"]
mysql = ["sqlx/mysql", "sqlx/time"]
sqlite-chrono = ["sqlx/sqlite", "sqlx/chrono"]
postgres-chrono = ["sqlx/postgres", "sqlx/chrono"]
mysql-chrono = ["sqlx/mysql", "sqlx/chrono"]
```

lib.rs:
```rust
#[cfg(any(feature = "mysql",feature = "mysql-chrono"))]
#[cfg_attr(docsrs, doc(cfg(any(feature = "mysql", feature = "mysql-chrono"))))]
pub use self::mysql_store::MySqlStore;
#[cfg(any(feature = "postgres",feature = "postgres-chrono"))]
#[cfg_attr(docsrs, doc(cfg(any(feature = "postgres", feature = "postgres-chrono"))))]
pub use self::postgres_store::PostgresStore;
#[cfg(any(feature = "sqlite",feature = "sqlite-chrono"))]
#[cfg_attr(docsrs, doc(cfg(any(feature = "sqlite", feature = "sqlite-chrono"))))]
pub use self::sqlite_store::SqliteStore;

#[cfg(any(feature = "sqlite", feature = "sqlite-chrono"))]
#[cfg_attr(docsrs, doc(cfg(any(feature = "sqlite", feature = "sqlite-chrono"))))]
mod sqlite_store;

#[cfg(feature = "postgres")]
#[cfg(any(feature = "postgres",feature = "postgres-chrono"))]
#[cfg_attr(docsrs, doc(cfg(any(feature = "postgres", feature = "postgres-chrono"))))]
mod postgres_store;

#[cfg(any(feature = "mysql",feature = "mysql-chrono"))]
#[cfg_attr(docsrs, doc(cfg(any(feature = "mysql", feature = "mysql-chrono"))))]
mod mysql_store;
```

The rest follows on the work done here, e.g.,
```rust
#[cfg(any(feature = "mysql", feature = "postgres", feature = "sqlite"))]
pub fn current_time() -> time::OffsetDateTime {
    time::OffsetDateTime::now_utc()
}

#[cfg(any(feature = "mysql-chrono", feature = "postgres-chrono", feature = "sqlite-chrono"))]
pub fn current_time() -> chrono::DateTime<chrono::Utc> {
    chrono::Utc::now()
}
```

**Comment by aschweig** [comment]
I had the idea to trivially take the outer-product of the various options, so one has both `feature = "sqlite"` and `feature = "sqlite-chrono"`, and the latter introduces the `SqliteChonoStore`; and similarly for mysql, and prostgres .  The feature (`time` or `chrono)` is simply passed on to sqlx without thinking too much -- though I am thinking maybe I just switch to `time`.  (I lifted most of my work from PR #46)

https://github.com/aschweig/tower-sessions-stores/tree/chronofix/sqlx-store

**Comment by nicolasauler** [comment]
Hey guys, has this been fixed? Or, can we fix it?

**Comment by karuna** [comment]
Maybe use my fork: https://crates.io/crates/tower-sessions-sqlx-store-chrono

**Pull request merged**
